### ISSUE TITLE
ERROR launching terminal command in Trim.py and Align.py

### ISSUE THREAD

**Issue by zanton123** [gdiminin/HaSAPPy#5]
Trim.py requires PreprocessReads in the current folder. If PreprocessRead is in the PATH change lines 21 and 34:
command = './PreprocessReads -i %s -o %s -len 25 -a %s -f' to command = 'PreprocessReads ...

**Comment by zanton123** [comment]
The following ERROR is generated even when PreprocessReads is in the current folder /HaSAPPy/HaSAPPy and can be started manually with the same command line:

./PreprocessReads -i /data/Monfort_2015/unselected/SRR2064917.fastq.gz -o /data/Monfort_2015/Ctrl1_2017-12-02/raw/Ctrl1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f

***	Trim adaptor and select for Quality	***
	Started: 17-12-02 16:45:08

Traceback (most recent call last):
  File "/HaSAPPy/HaSAPPy/HaSAPPy", line 40, in <module>
    Trim.load(analysis)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Trim.py", line 22, in load
    run_output = subprocess.check_output(command,shell= True,stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command './PreprocessReads -i /data/Monfort_2015/unselected/SRR2064917.fastq.gz -o /data/Monfort_2015/Ctrl1_2017-12-02/raw/Ctrl1_QS.fastq -len 25 -a ATCTCGTATGCCGTCTTCTGCTT -f' returned non-zero exit status 127

**Comment by zanton123** [comment]
seems like a more general issue with calling terminal processes in the docker image. There are 2 errors from attempting analyse.sh Jae_2013 and Staring_2017:

1.
Ctrl
Align to Reference genome:
	Started: 17-12-02 17:22:37
Traceback (most recent call last):
  File "/HaSAPPy/HaSAPPy/HaSAPPy", line 44, in <module>
    Align.load(analysis)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Align.py", line 157, in load
    Align_library(Info,Info.AlignGenome,exp,storing_loc,storing_suffix,program = Info.AlignGenome.program_type,pair_end = Info.General.pair_ends)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Align.py", line 56, in Align_library
    run_output = subprocess.check_output(command,shell= True,stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'bowtie2 --time --local --threads 8 -x /data/reference/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/genome -U /data/Jae_2013/unselected/SRR663777.fastq -S /data/Jae_2013/Ctrl_2017-12-02/raw/Ctrl_Aligned.sam' returned non-zero exit status 1

2.
Align to Reference genome:
	Started: 17-12-02 17:23:18
Traceback (most recent call last):
  File "/HaSAPPy/HaSAPPy/HaSAPPy", line 44, in <module>
    Align.load(analysis)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Align.py", line 157, in load
    Align_library(Info,Info.AlignGenome,exp,storing_loc,storing_suffix,program = Info.AlignGenome.program_type,pair_end = Info.General.pair_ends)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Align.py", line 56, in Align_library
    run_output = subprocess.check_output(command,shell= True,stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'bowtie2 --time --local --threads 8 -x /data/reference/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/genome -U /data/Staring_2017/unselected/SRR663777.fastq -S /data/Staring_2017/Ctrl_2017-12-02/raw/Ctrl_Aligned.sam' returned non-zero exit status 1

**Comment by gdiminin** [comment]
Thanks for using HaSAPPy. The errors were fixed in the latest update.
