### ISSUE TITLE
Possible bug with rankAnalysis

### ISSUE THREAD

**Issue by pmoulos** [gdiminin/HaSAPPy#6]
Hello,

I am trying to perform the standard workflow of HaSAPPy, with the only difference of starting with my own alignment SAM files. After finishing with insertion localization, the program fails with the following:

```
The file has been used for the following analysis:
Traceback (most recent call last):
  File "HaSAPPY.py", line 54, in <module>
    import HaSAPPy.GroupAnalysis as GroupAnalysis
  File "build/bdist.linux-x86_64/egg/HaSAPPy/GroupAnalysis.py", line 15, in <module>
    import HaSAPPy.rankAnalysis as rankAnalysis
ImportError: No module named rankAnalysis
```
Looking at the latest [commit](https://github.com/gdiminin/HaSAPPy/commit/f088f3de8cf5feb872385a6f7f2d14f7ceb381a8), the following line was added in [HaSAPPy/GroupAnalysis.py](https://github.com/gdiminin/HaSAPPy/commit/f088f3de8cf5feb872385a6f7f2d14f7ceb381a8#diff-72e48209637f0e04149fcf5b9b36e573):

```
import HaSAPPy.rankAnalysis as rankAnalysis
```

I am not a Python expert, however I can't locate the funcion/module rankAnalysis anywhere. Could this be a bug? Thanks in advance.

Panagiotis

**Comment by gdiminin** [comment]
Hi,
Thanks for the notice. During the upload the file was lost! Now the issue should be fixed.
Giulio
